/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'akoiro' at '8/27/15 9:37 PM' with Gradle 2.6
 *
 * @author akoiro, @date 8/27/15 9:37 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
